spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode&encodeing=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081